-- Copyright (C) 2026  Pierre Ardoin <developpeur@lesmetiersdubatiment.fr>
--
-- Weekly report main table.

CREATE TABLE llx_saweeklyreport_weeklyreport(
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	entity integer DEFAULT 1 NOT NULL,
	ref varchar(128) NOT NULL,
	label varchar(255),
	year integer NOT NULL,
	week integer NOT NULL,
	period_start date NOT NULL,
	period_end date NOT NULL,
	month_start date,
	month_end date,
	meeting_duration integer DEFAULT 15,
	week_installed_power double(24,8) DEFAULT 0,
	month_installed_power double(24,8) DEFAULT 0,
	annual_installed_power double(24,8) DEFAULT 0,
	annual_target_power double(24,8) DEFAULT 846,
	weekly_target_power double(24,8) DEFAULT 18,
	annual_completion_rate double(24,8) DEFAULT 0,
	annual_average_power double(24,8) DEFAULT 0,
	workweeks_elapsed double(24,8) DEFAULT 0,
	technician_days double(24,8) DEFAULT 0,
	technician_workdays double(24,8) DEFAULT 5,
	technician_average double(24,8) DEFAULT 0,
	previous_week_feedback text,
	current_week_goal text,
	field_returns text,
	safety_message text,
	vehicle_loading_reminder text,
	source_snapshot mediumtext,
	note_public text,
	note_private text,
	date_creation datetime NOT NULL,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer NOT NULL,
	fk_user_modif integer,
	last_main_doc varchar(255),
	import_key varchar(14),
	model_pptx varchar(255),
	status integer NOT NULL DEFAULT 0
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
